version: '3.2'

services:
    # api server
    flask:
        build:
            context: ./flask
        ports:
            - 3000:3000
        container_name: flask
        restart: always
        networks:
            - app_tier
        volumes:
            - ./flask:/app
        command: gunicorn -w 1 -b 0.0.0.0:3000 run:app

    # web server
    nginx:
        image: nginx:latest
        ports:
            - 8000:8000
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - flask
        networks:
            - app_tier
        restart: on-failure

    #elasticsearch
    elasticsearch:
        build:
            context: ./ELK/elasticsearch
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - app_tier
        volumes:
            - type: bind
              source: ./ELK/elasticsearch/config/elasticsearch.yml
              target: /usr/share/elasticsearch/config/elasticsearch.yml
              read_only: true
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: "123456"
            discovery.type: single-node
        healthcheck:
            test: "curl http://elasticsearch:9200"
            interval: "1s"
            timeout: "3s"
            retries: 60
        ulimits:
            memlock:
                soft: -1
                hard: -1

    #logastash
    logstash:
        build:
            context: ./ELK/logstash
        ports:
            - 5044:5044
            - 5000:5000/tcp
            - 5000:5000/udp
            - 9600:9600
        volumes:
            - type: bind
              source: ./ELK/logstash/config/logstash.yml
              target: /usr/share/logstash/config/logstash.yml
              read_only: true

            - type: bind
              source: ./ELK/logstash/pipeline
              target: /usr/share/logstash/pipeline
              read_only: true    
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - app_tier
        depends_on:
            - elasticsearch
    
    #kibana
    kibana:
        build:
            context: ./ELK/kibana/
        ports:
            - 5601:5601
        volumes:
            - type: bind
              source: ./ELK/kibana/config/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        networks:
            - app_tier
        depends_on:
            - elasticsearch        

networks:
    app_tier:
        driver: bridge


        